#!/usr/bin/env python3
"""
build_content.py — content build step.

Reads the editable Markdown sources in content/*.md plus content/manifest.json and
emits html-export/assets/content.js, which inlines every module's Markdown into a
single JS global (window.SDET_CONTENT). Inlining (vs. fetch) is what lets the SPA
run straight from file:// where Chrome blocks fetch() by CORS.

Run from the repo root:  python3 tools/build_content.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = ROOT / "content"
OUT = ROOT / "html-export" / "assets" / "content.js"


def main() -> None:
    manifest = json.loads((CONTENT_DIR / "manifest.json").read_text("utf-8"))

    modules = {}
    for course in manifest["courses"]:
        for m in course["modules"]:
            slug = m["slug"]
            md_path = CONTENT_DIR / f"{slug}.md"
            if not md_path.exists():
                raise SystemExit(f"Missing markdown source: {md_path}")
            modules[slug] = {
                "slug": slug,
                "num": m.get("num", ""),
                "title": m.get("title", ""),
                "crumb": m.get("crumb", ""),
                "markdown": md_path.read_text("utf-8"),
            }

    payload = {"courses": manifest["courses"], "modules": modules}
    js = (
        "// GENERATED by tools/build_content.py — do not edit by hand.\n"
        "// Edit content/*.md then rerun: python3 tools/build_content.py\n"
        "window.SDET_CONTENT = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js, encoding="utf-8")

    n_mod = len(modules)
    print(f"Wrote {OUT.relative_to(ROOT)}  ({n_mod} módulos, {OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
